config/routes.rb
Rails.application.routes.draw do
  get '/show_foreign_amazonprime', to: 'static_pages#show_foreign_amazonprime'
  get '/show_foreign_netflix', to: 'static_pages#show_foreign_netflix'
  get '/show_foreign_hulu', to: 'static_pages#show_foreign_hulu'
  get '/show_japanese_amazonprime', to: 'static_pages#show_japanese_amazonprime'
  get '/show_japanese_netflix', to: 'static_pages#show_japanese_netflix'
  get '/show_japanese_hulu', to: 'static_pages#show_japanese_hulu'
  get '/show_anime_amazonprime', to: 'static_pages#show_anime_amazonprime'
  get '/show_anime_netflix', to: 'static_pages#show_anime_netflix'
  get '/show_anime_hulu', to: 'static_pages#show_anime_hulu'
  resources :movies do
    resources :reviews
  end
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  validates :name, presence: true, length: {maximum: 30}
  validates :score, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  # 映画一覧の表示
  def show
    @movie = Movie.find(params[:id])
    @review = Review.new
  end
  

private
  # ストロングパラメーター
  def  movie_params
    params.require(:movie).permit(:title, :genre,
                                :description, :app, :review_score)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  # レビューの投稿
  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
    if @review.update(review_params)
      flash[:success] = '投稿が完了しました'
      redirect_to movie_path(@movie)
      @movie.review_score = @movie.reviews.average(:score).round(1)
      @movie.save
    else
      flash[:danger] = '正しく入力してください'
      redirect_to movie_path(@movie)
    end
  end
      
private
  # ストロングパラメーター
  def  review_params
    params.require(:review).permit(:name, :content, :score, :movie_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show_foreign_amazonprime
    show_movie('amazon_prime', '海外映画')
  end

  def show_foreign_netflix
    show_movie('netflix', '海外映画')
  end

  def show_foreign_hulu
    show_movie('hulu', '海外映画')
  end

  def show_japanese_amazonprime
    show_movie('amazon_prime', '日本映画')
  end

  def show_japanese_netflix
    show_movie('netflix', '日本映画')
  end

  def show_japanese_hulu
    show_movie('hulu', '日本映画')
  end
  
  def show_anime_amazonprime
    show_movie('amazon_prime', 'アニメ')
  end
  
  def show_anime_netflix
    show_movie('netflix', 'アニメ')
  end
  
  def show_anime_hulu
    show_movie('hulu', 'アニメ')
  end
  
  
# 映画の一覧表示
  def show_movie(app, movie_type)
    if params[:search].nil? # 検索していない場合
      @movies = Movie.where(app: app, movie_type: movie_type).order(review_score: :desc)
    elsif params[:search][:title] && params[:search][:genre] == '' # タイトルのみ検索している場合
      @movies = Movie.where(app: app, movie_type: movie_type).where("title LIKE ?", "%#{params[:search][:title]}%")
      .order(review_score: :desc)
    elsif params[:search][:genre] && params[:search][:title] == '' # ジャンルで検索している場合
      @movies = Movie.where(app: app, movie_type: movie_type).where("genre LIKE ?", "%#{params[:search][:genre]}%")
      .order(review_score: :desc)
    else # ジャンルとタイトル両方で検索している場合
      @movies = Movie.where(app: app, movie_type: movie_type).where("genre LIKE ?", "%#{params[:search][:genre]}%")
      .where("title LIKE ?", "%#{params[:search][:title]}%").order(review_score: :desc)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページのタイトルを取得
  def full_title(page_title='')
    base_title = 'MovieAppReview'
    if page_title.empty?
      base_title
    else
      page_title + '|' + base_title
    end
  end
end

app/views/layouts/_header.html.erb
<header>
  
    <div class='top'>
    <h1>MovieAppReview</h1>
    <h2>映画アプリの映画レビューサイト</h2>
    </div>
    
    
    <div class='menu'>
    <nav class="navbar navbar-expand-lg navbar-light">
        <%= link_to 'Home', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
            <%= link_to 'Amazon prime', show_foreign_amazonprime_path, class: "nav-link active　dropdown-toggle", id: "navbarDropdownMenuLink", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to '海外映画', show_foreign_amazonprime_path, class: 'dropdown-item' %>
            <%= link_to '日本映画', show_japanese_amazonprime_path, class: 'dropdown-item' %>
            <%= link_to 'アニメ', show_anime_amazonprime_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item dropdown">
            <%= link_to 'Hulu', show_foreign_hulu_path, class: "nav-link active　dropdown-toggle", id: "navbarDropdownMenuLink", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to '海外映画', show_foreign_hulu_path, class: 'dropdown-item' %>
            <%= link_to '日本映画', show_japanese_hulu_path, class: 'dropdown-item' %>
            <%= link_to 'アニメ', show_anime_hulu_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item dropdown">
            <%= link_to 'Netflix', show_foreign_netflix_path, class: "nav-link active　dropdown-toggle", id: "navbarDropdownMenuLink", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to '海外映画', show_foreign_netflix_path, class: 'dropdown-item' %>
            <%= link_to '日本映画', show_japanese_netflix_path, class: 'dropdown-item' %>
            <%= link_to 'アニメ', show_anime_netflix_path, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  </div>
</header>
<hr>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/static_pages/show_anime_amazonprime.html.erb
<% provide(:title, 'Amazon prime') %>
<% provide(:app_title, 'Amazon prime') %>
<div class='search-form'>
<%= form_with url: show_anime_amazonprime_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'アニメ': 'アニメ',
}%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_anime_hulu.html.erb
<% provide(:title, 'Hulu') %>
<% provide(:app_title, 'Hulu') %>
<div class='search-form'>
<%= form_with url: show_anime_hulu_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'SF': 'SF',
'戦争': '戦争',
'アドベンチャー': 'アドベンチャー',
'史劇': '史劇',
'音楽／ライブ': '音楽／ライブ',
'キッズ': 'キッズ',
'サスペンス／ミステリー': 'サスペンス／ミステリー',
'青春': '青春',
'アニメ': 'アニメ',
'ファンタジー': 'ファンタジー',
'恋愛': '恋愛',
'ヒューマンドラマ': 'ヒューマンドラマ',
'コメディ': 'コメディ',
'スポーツ': 'スポーツ',
'ファミリー': 'ファミリー',
'アクション': 'アクション',
'時代劇': '時代劇',
}
%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_anime_netflix.html.erb
<% provide(:title, 'Netflix') %>
<% provide(:app_title, 'Netflix') %>
<div class='search-form'>
<%= form_with url: show_anime_netflix_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'日本アカデミー賞受賞映画': '日本アカデミー賞受賞映画',
'キッズアニメ': 'キッズアニメ',
'劇場版アニメ': '劇場版アニメ',
'国内SF・ファンタジー': '国内SF・ファンタジー',
'キッズTV番組': 'キッズTV番組',
'TVアニメ': 'TVアニメ',
'2018年アニメ': '2018年アニメ',
'SF・ファンタジーアニメ': 'SF・ファンタジーアニメ',
'歴史・時代劇': '歴史・時代劇',
'恋愛アニメ': '恋愛アニメ',
'主人公最強アニメ': '主人公最強アニメ',
'キッズ・ファミリー映画': 'キッズ・ファミリー映画',
'SF・サイバーパンク': 'SF・サイバーパンク',
'スポーツアニメ': 'スポーツアニメ',
'サスペンス・ホラーアニメ': 'サスペンス・ホラーアニメ',
'国内アクション・アドベンチャー': '国内アクション・アドベンチャー',
'ゲーマーにオススメのアニメ': 'ゲーマーにオススメのアニメ',
'青春・学園アニメ': '青春・学園アニメ',
'ライトノベルが原作のアニメ': 'ライトノベルが原作のアニメ',
'ミリタリー・戦争アニメ': 'ミリタリー・戦争アニメ',
'アニメ': 'アニメ',
'2017年アニメ': '2017年アニメ',
'ロボット・サイボーグアニメ': 'ロボット・サイボーグアニメ',
'ビデオゲームが原作のアニメ': 'ビデオゲームが原作のアニメ',
'キッズ音楽': 'キッズ音楽',
'週刊少年ジャンプが原作のアニメ': '週刊少年ジャンプが原作のアニメ',
'歴史アニメ': '歴史アニメ',
'アクションアニメ': 'アクションアニメ',
'コメディ・ギャグアニメ': 'コメディ・ギャグアニメ',
'アクションコメディ': 'アクションコメディ',
'漫画が原作のアニメ': '漫画が原作のアニメ',
}%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_foreign_amazonprime.html.erb
<% provide(:title, 'Amazon prime') %>
<% provide(:app_title, 'Amazon prime') %>
<div class='search-form'>
<%= form_with url: show_foreign_amazonprime_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
  ジャンル:<%= f.select :genre,
  {'選択して下さい': nil,
  'SF': 'SF',
  'アニメ': 'アニメ',
  'ドキュメンタリー': 'ドキュメンタリー',
  'ホビー・実用': 'ホビー・実用',
  'ファンタジー': 'ファンタジー',
  'サスペンス': 'サスペンス',
  'ロマンス': 'ロマンス',
  'スポーツ': 'スポーツ',
  'アドベンチャー': 'アドベンチャー',
  'アクション': 'アクション',
  'アート・エンターテイメント・カルチャー': 'アート・エンターテイメント・カルチャー',
  'ホラー': 'ホラー',
  '外国映画': '外国映画',
  'キッズ': 'キッズ',
  '軍隊・戦争': '軍隊・戦争',
  'コメディー': 'コメディー',
  'ドラマ': 'ドラマ',
  'ミュージックビデオ・コンサート': 'ミュージックビデオ・コンサート',
  '歴史': '歴史',
  'エロティック': 'エロティック',
  '西部劇': '西部劇',
  }%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_foreign_hulu.html.erb
<% provide(:title, 'Hulu') %>
<% provide(:app_title, 'Hulu') %>
<div class='search-form'>
<%= form_with url: show_foreign_hulu_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'時代劇': '時代劇',
'史劇': '史劇',
'音楽／ライブ': '音楽／ライブ',
'西部劇': '西部劇',
'コメディ': 'コメディ',
'スポーツ': 'スポーツ',
'アクション': 'アクション',
'ヒューマンドラマ': 'ヒューマンドラマ',
'恋愛': '恋愛',
'SF': 'SF',
'アドベンチャー': 'アドベンチャー',
'特撮': '特撮',
'ファンタジー': 'ファンタジー',
'戦争': '戦争',
'パニック': 'パニック',
'青春': '青春',
'サスペンス／ミステリー': 'サスペンス／ミステリー',
'キッズ': 'キッズ',
'ドキュメンタリー': 'ドキュメンタリー',
'ホラー': 'ホラー',
'ファミリー': 'ファミリー',
'アニメ': 'アニメ',
}
%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_foreign_netflix.html.erb
<% provide(:title, 'Netflix') %>
<% provide(:app_title, 'Netflix') %>
<div class='search-form'>
<%= form_with url: show_foreign_netflix_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'韓国/ラブロマンス': '韓国/ラブロマンス',
'イタリア映画': 'イタリア映画',
'アメリカ映画': 'アメリカ映画',
'台湾映画': '台湾映画',
'コメディ': 'コメディ',
'実話に基づくヒューマンドラマ': '実話に基づくヒューマンドラマ',
'マインドゲームスリラー': 'マインドゲームスリラー',
'実際に起きた犯罪事件を描くドキュメンタリー': '実際に起きた犯罪事件を描くドキュメンタリー',
'ティーン向けホラー': 'ティーン向けホラー',
'ホラー': 'ホラー',
'受賞歴のある映画': '受賞歴のある映画',
'ファンタジー': 'ファンタジー',
'北欧映画': '北欧映画',
'法廷ヒューマンドラマ': '法廷ヒューマンドラマ',
'海外SF・ファンタジー': '海外SF・ファンタジー',
'キネマ旬報ベスト・テン受賞映画': 'キネマ旬報ベスト・テン受賞映画',
'ティーン向け恋愛・ラブストーリー': 'ティーン向け恋愛・ラブストーリー',
'中東映画': '中東映画',
'インド映画': 'インド映画',
'ベネチア国際映画祭受賞映画': 'ベネチア国際映画祭受賞映画',
'ゾンビホラー': 'ゾンビホラー',
'強盗アクション': '強盗アクション',
'海外TV番組・ドラマ': '海外TV番組・ドラマ',
'コミカルなコメディ': 'コミカルなコメディ',
'SFヒューマンドラマ': 'SFヒューマンドラマ',
'ビジネスをテーマにしたドキュメンタリー': 'ビジネスをテーマにしたドキュメンタリー',
'青春・学園': '青春・学園',
'海外ラブロマンス': '海外ラブロマンス',
'自然・生態系ドキュメンタリー': '自然・生態系ドキュメンタリー',
'ラブロマンス': 'ラブロマンス',
'スポーツドキュメンタリー': 'スポーツドキュメンタリー',
'大人向けアニメ': '大人向けアニメ',
'超常現象ホラー': '超常現象ホラー',
'海外/サスペンス': '海外/サスペンス',
'海外LGBTQ映画': '海外LGBTQ映画',
'アドベンチャー': 'アドベンチャー',
'スタンドアップコメディ': 'スタンドアップコメディ',
'ダークコメディ': 'ダークコメディ',
'欧米大ヒット映画': '欧米大ヒット映画',
'イギリス映画': 'イギリス映画',
'アニメーション': 'アニメーション',
'武術映画': '武術映画',
'SFサスペンス': 'SFサスペンス',
'バラエティ': 'バラエティ',
'海外ホラー': '海外ホラー',
'科学・技術ドキュメンタリー': '科学・技術ドキュメンタリー',
'カンヌ国際映画祭受賞映画': 'カンヌ国際映画祭受賞映画',
'海外/コメディ': '海外/コメディ',
'インディーズ系ヒューマンドラマ': 'インディーズ系ヒューマンドラマ',
'サスペンス': 'サスペンス',
'アクションコメディ': 'アクションコメディ',
'吸血鬼ホラー': '吸血鬼ホラー',
'香港映画': '香港映画',
'カナダ/TV番組・ドラマ': 'カナダ/TV番組・ドラマ',
'犯罪アクション・アドベンチャー': '犯罪アクション・アドベンチャー',
'ギャング・任侠の世界を描いたアクション': 'ギャング・任侠の世界を描いたアクション',
'高い評価を得た映画': '高い評価を得た映画',
'マラーティー語の映画': 'マラーティー語の映画',
'アニメ': 'アニメ',
'Urdu-Language Movies': 'Urdu-Language Movies',
'リトルキッズ': 'リトルキッズ',
'伝記ヒューマンドラマ': '伝記ヒューマンドラマ',
'ドイツ映画': 'ドイツ映画',
'海外/ヒューマンドラマ': '海外/ヒューマンドラマ',
'ウェスタン': 'ウェスタン',
'SFアクション': 'SFアクション',
'児童書が原作の映画': '児童書が原作の映画',
'海外/名作映画': '海外/名作映画',
'スペイン映画': 'スペイン映画',
'海外/アクション・アドベンチャー': '海外/アクション・アドベンチャー',
'政治をテーマにしたヒューマンドラマ': '政治をテーマにしたヒューマンドラマ',
'軍隊・戦争系アクション': '軍隊・戦争系アクション',
'音楽・ミュージカル': '音楽・ミュージカル',
'歴史・時代劇': '歴史・時代劇',
'泣けるラブロマンス': '泣けるラブロマンス',
'大ヒットSF・ファンタジー': '大ヒットSF・ファンタジー',
'ラブコメディ': 'ラブコメディ',
'動物物語': '動物物語',
'犯罪ヒューマンドラマ': '犯罪ヒューマンドラマ',
'本が原作のヒューマンドラマ': '本が原作のヒューマンドラマ',
'アクション・アドベンチャー': 'アクション・アドベンチャー',
'ディズニー映画': 'ディズニー映画',
'タイムトラベル': 'タイムトラベル',
'ミステリー': 'ミステリー',
'ベンガル語の映画': 'ベンガル語の映画',
'官能的なラブロマンス': '官能的なラブロマンス',
'キッズ・ファミリー映画': 'キッズ・ファミリー映画',
'中南米映画': '中南米映画',
'アカデミー賞受賞映画': 'アカデミー賞受賞映画',
'海外映画': '海外映画',
'カナダ映画': 'カナダ映画',
'海外ドキュメンタリー': '海外ドキュメンタリー',
'ロマンチックなヒューマンドラマ': 'ロマンチックなヒューマンドラマ',
'心理サスペンス': '心理サスペンス',
'ヒューマンドラマ': 'ヒューマンドラマ',
'ノルウェー映画': 'ノルウェー映画',
'名作映画': '名作映画',
'アジア映画': 'アジア映画',
}%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_japanese_amazonprime.html.erb
<% provide(:title, 'Amazon prime') %>
<% provide(:app_title, 'Amazon prime') %>
<div class='search-form'>
<%= form_with url: show_japanese_amazonprime_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'アニメ': 'アニメ',
'軍隊・戦争': '軍隊・戦争',
'コメディー': 'コメディー',
'キッズ': 'キッズ',
'アートシアター': 'アートシアター',
'三池崇史': '三池崇史',
'ファンタジー': 'ファンタジー',
'ドキュメンタリー': 'ドキュメンタリー',
'ミュージックビデオ・コンサート': 'ミュージックビデオ・コンサート',
'外国映画': '外国映画',
'SF': 'SF',
'アドベンチャー': 'アドベンチャー',
'ホラー': 'ホラー',
'ドラマ': 'ドラマ',
'サスペンス': 'サスペンス',
'ロマンス': 'ロマンス',
'アクション': 'アクション',
}%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_japanese_hulu.html.erb
<% provide(:title, 'Hulu') %>
<% provide(:app_title, 'Hulu') %>
<div class='search-form'>
<%= form_with url: show_japanese_hulu_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'史劇': '史劇',
'西部劇': '西部劇',
'ホラー': 'ホラー',
'時代劇': '時代劇',
'アドベンチャー': 'アドベンチャー',
'アニメ': 'アニメ',
'サスペンス／ミステリー': 'サスペンス／ミステリー',
'旅行／趣味': '旅行／趣味',
'ファミリー': 'ファミリー',
'特撮': '特撮',
'キッズ': 'キッズ',
'ヒューマンドラマ': 'ヒューマンドラマ',
'コメディ': 'コメディ',
'スポーツ': 'スポーツ',
'音楽／ライブ': '音楽／ライブ',
'アクション': 'アクション',
'青春': '青春',
'バラエティ': 'バラエティ',
'ファンタジー': 'ファンタジー',
'ドキュメンタリー': 'ドキュメンタリー',
'料理': '料理',
'戦争': '戦争',
'SF': 'SF',
'パニック': 'パニック',
'恋愛': '恋愛',
}
%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>

app/views/static_pages/show_japanese_netflix.html.erb
<% provide(:title, 'Netflix') %>
<% provide(:app_title, 'Netflix') %>
<div class='search-form'>
<%= form_with url: show_japanese_netflix_path, scope: :search, method: :get, local: true do |f| %>
<div class='search-box'>タイトル:<%= f.text_field :title, class: 'search-box' %></div>
<div class='select-box'>
ジャンル:<%= f.select :genre,
{'選択して下さい': nil,
'ホラー': 'ホラー',
'スポーツアニメ': 'スポーツアニメ',
'犯罪サスペンス': '犯罪サスペンス',
'国内コメディ': '国内コメディ',
'社会問題に迫るヒューマンドラマ': '社会問題に迫るヒューマンドラマ',
'国内任侠映画': '国内任侠映画',
'国内アクション・アドベンチャー': '国内アクション・アドベンチャー',
'キッズ・ファミリー映画': 'キッズ・ファミリー映画',
'漫画が原作の国内映画': '漫画が原作の国内映画',
'ヒューマンドラマ': 'ヒューマンドラマ',
'アクションコメディ': 'アクションコメディ',
'ファンタジー': 'ファンタジー',
'本が原作のヒューマンドラマ': '本が原作のヒューマンドラマ',
'国内ドキュメンタリー': '国内ドキュメンタリー',
'官能的なラブロマンス': '官能的なラブロマンス',
'国内ヒューマンドラマ': '国内ヒューマンドラマ',
'音楽・ミュージカル': '音楽・ミュージカル',
'コメディ': 'コメディ',
'政治ドキュメンタリー': '政治ドキュメンタリー',
'インディーズ映画': 'インディーズ映画',
'コミカルなコメディ': 'コミカルなコメディ',
'アニメ': 'アニメ',
'法廷ヒューマンドラマ': '法廷ヒューマンドラマ',
'国内青春・学園': '国内青春・学園',
'ロボット・サイボーグアニメ': 'ロボット・サイボーグアニメ',
'ミステリー': 'ミステリー',
'ショービジネスの世界を描いたドキュメンタリー': 'ショービジネスの世界を描いたドキュメンタリー',
'ティーン向けホラー': 'ティーン向けホラー',
'日本アカデミー賞受賞映画': '日本アカデミー賞受賞映画',
'LGBTQを描いたヒューマンドラマ': 'LGBTQを描いたヒューマンドラマ',
'歴史・時代劇': '歴史・時代劇',
'国内SF・ファンタジー': '国内SF・ファンタジー',
'サスペンス': 'サスペンス',
'スポーツをテーマにしたヒューマンドラマ': 'スポーツをテーマにしたヒューマンドラマ',
'高い評価を得た映画': '高い評価を得た映画',
'歴史ドキュメンタリー': '歴史ドキュメンタリー',
'官能的なヒューマンドラマ': '官能的なヒューマンドラマ',
'文化・社会ドキュメンタリー': '文化・社会ドキュメンタリー',
'国内時代劇': '国内時代劇',
'ティーン向け恋愛・ラブストーリー': 'ティーン向け恋愛・ラブストーリー',
'キッズ音楽': 'キッズ音楽',
'主人公最強アニメ': '主人公最強アニメ',
'政治をテーマにしたヒューマンドラマ': '政治をテーマにしたヒューマンドラマ',
'ラブロマンス': 'ラブロマンス',
'キッズアニメ': 'キッズアニメ',
'コメディ・ギャグアニメ': 'コメディ・ギャグアニメ',
'実話に基づくヒューマンドラマ': '実話に基づくヒューマンドラマ',
'ドラマアニメ': 'ドラマアニメ',
'国内サスペンス': '国内サスペンス',
'ブルーリボン賞受賞映画': 'ブルーリボン賞受賞映画',
'国内バラエティ・お笑い': '国内バラエティ・お笑い',
'特撮・ヒーロー': '特撮・ヒーロー',
'国内名作映画': '国内名作映画',
'マインドゲームスリラー': 'マインドゲームスリラー',
'国内犯罪捜査': '国内犯罪捜査',
'ビデオゲームが原作のアニメ': 'ビデオゲームが原作のアニメ',
'ロマンチックなヒューマンドラマ': 'ロマンチックなヒューマンドラマ',
'国内映画': '国内映画',
'泣けるラブロマンス': '泣けるラブロマンス',
'ラブコメディ': 'ラブコメディ',
'ドキュメンタリー': 'ドキュメンタリー',
}%>
</div>
<%= f.submit '検索', class: 'btn btn-primary', name: nil %>
<% end %>
</div>
<%= render 'show' %>